import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Hero from "./components/hero";
import Management from "./components/management";
import Extension from "./components/extension";
import Footer from "./components/footer";
import Customize from "./components/custom";
import Work from "./components/work";
import Sponsers from "./components/sponser";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero />
        <Management />
        <Extension />
        <Customize />
			  <Work/>
			  <Sponsers/>
        <Footer />
      </body>
    </html>
  );
}
